const countryIdToCountry = {
  1: { countryCode: 'US', countryName: 'United States' },
  2185: { countryCode: 'AF', countryName: 'Afghanistan' },
  2186: { countryCode: 'AL', countryName: 'Albania' },
  2187: { countryCode: 'DZ', countryName: 'Algeria' },
  2188: { countryCode: 'AD', countryName: 'Andorra' },
  2189: { countryCode: 'AO', countryName: 'Angola' },
  2190: { countryCode: 'AQ', countryName: 'Antarctica' },
  2191: { countryCode: 'AG', countryName: 'Antigua and Barbuda' },
  2192: { countryCode: 'AR', countryName: 'Argentina' },
  2193: { countryCode: 'AM', countryName: 'Armenia' },
  2194: { countryCode: 'AU', countryName: 'Australia' },
  2195: { countryCode: 'AT', countryName: 'Austria' },
  2196: { countryCode: 'AZ', countryName: 'Azerbaijan' },
  2197: { countryCode: 'BS', countryName: 'Bahamas' },
  2198: { countryCode: 'BH', countryName: 'Bahrain' },
  2199: { countryCode: 'BD', countryName: 'Bangladesh' },
  2200: { countryCode: 'BB', countryName: 'Barbados' },
  2201: { countryCode: 'BY', countryName: 'Belarus' },
  2202: { countryCode: 'BE', countryName: 'Belgium' },
  2203: { countryCode: 'BZ', countryName: 'Belize' },
  2204: { countryCode: 'BJ', countryName: 'Benin' },
  2205: { countryCode: 'BT', countryName: 'Bhutan' },
  2206: { countryCode: 'BO', countryName: 'Bolivia; Plurinational State' },
  2207: { countryCode: 'BA', countryName: 'Bosnia and Herzegovina' },
  2208: { countryCode: 'BW', countryName: 'Botswana' },
  2209: { countryCode: 'BR', countryName: 'Brazil' },
  2210: { countryCode: 'BN', countryName: 'Brunei Darussalam' },
  2211: { countryCode: 'BG', countryName: 'Bulgaria' },
  2212: { countryCode: 'BF', countryName: 'Burkina Faso' },
  2213: { countryCode: 'BI', countryName: 'Burundi' },
  2214: { countryCode: 'KH', countryName: 'Cambodia' },
  2215: { countryCode: 'CM', countryName: 'Cameroon' },
  2216: { countryCode: 'CA', countryName: 'Canada' },
  2217: { countryCode: 'CV', countryName: 'Cape Verde' },
  2218: { countryCode: 'CF', countryName: 'Central African Republic' },
  2219: { countryCode: 'TD', countryName: 'Chad' },
  2220: { countryCode: 'CL', countryName: 'Chile' },
  2221: { countryCode: 'CN', countryName: 'China' },
  2222: { countryCode: 'CO', countryName: 'Colombia' },
  2226: { countryCode: 'CR', countryName: 'Costa Rica' },
  2227: { countryCode: 'CI', countryName: 'Cote D\'Ivoire' },
  2228: { countryCode: 'HR', countryName: 'Croatia' },
  2230: { countryCode: 'CY', countryName: 'Cyprus' },
  2231: { countryCode: 'CZ', countryName: 'Czech Republic' },
  2232: { countryCode: 'DK', countryName: 'Denmark' },
  2233: { countryCode: 'DJ', countryName: 'Djibouti' },
  2234: { countryCode: 'DM', countryName: 'Dominica' },
  2235: { countryCode: 'DO', countryName: 'Dominican Republic' },
  2236: { countryCode: 'EC', countryName: 'Ecuador' },
  2237: { countryCode: 'EG', countryName: 'Egypt' },
  2238: { countryCode: 'SV', countryName: 'El Salvador' },
  2239: { countryCode: 'GQ', countryName: 'Equatorial Guinea' },
  2240: { countryCode: 'ER', countryName: 'Eritrea' },
  2241: { countryCode: 'EE', countryName: 'Estonia' },
  2242: { countryCode: 'ET', countryName: 'Ethiopia' },
  2243: { countryCode: 'FJ', countryName: 'Fiji' },
  2244: { countryCode: 'FI', countryName: 'Finland' },
  2245: { countryCode: 'FR', countryName: 'France' },
  2246: { countryCode: 'GA', countryName: 'Gabon' },
  2248: { countryCode: 'GE', countryName: 'Georgia' },
  2249: { countryCode: 'DE', countryName: 'Germany' },
  2250: { countryCode: 'GH', countryName: 'Ghana' },
  2251: { countryCode: 'GR', countryName: 'Greece' },
  2252: { countryCode: 'GL', countryName: 'Greenland' },
  2253: { countryCode: 'GD', countryName: 'Grenada' },
  2255: { countryCode: 'GN', countryName: 'Guinea' },
  2256: { countryCode: 'GW', countryName: 'Guinea-Bissau' },
  2257: { countryCode: 'GY', countryName: 'Guyana' },
  2258: { countryCode: 'HT', countryName: 'Haiti' },
  2259: { countryCode: 'HN', countryName: 'Honduras' },
  2260: { countryCode: 'HU', countryName: 'Hungary' },
  2261: { countryCode: 'IS', countryName: 'Iceland' },
  2262: { countryCode: 'IN', countryName: 'India' },
  2263: { countryCode: 'ID', countryName: 'Indonesia' },
  2264: { countryCode: 'IR', countryName: 'Iran; Islamic Republic of' },
  2265: { countryCode: 'IQ', countryName: 'Iraq' },
  2266: { countryCode: 'IE', countryName: 'Ireland' },
  2267: { countryCode: 'IL', countryName: 'Israel' },
  2268: { countryCode: 'IT', countryName: 'Italy' },
  2269: { countryCode: 'JM', countryName: 'Jamaica' },
  2270: { countryCode: 'JP', countryName: 'Japan' },
  2271: { countryCode: 'JO', countryName: 'Jordan' },
  2272: { countryCode: 'KZ', countryName: 'Kazakhstan' },
  2273: { countryCode: 'KE', countryName: 'Kenya' },
  2274: { countryCode: 'KP', countryName: 'Korea; Democratic People\'s Republic Of (North)' },
  2275: { countryCode: 'KR', countryName: 'Korea; Republic Of (South)' },
  2276: { countryCode: 'KW', countryName: 'Kuwait' },
  2277: { countryCode: 'KG', countryName: 'Kyrgyzstan' },
  2278: { countryCode: 'LA', countryName: 'Lao People\'s Democratic Republic' },
  2279: { countryCode: 'LV', countryName: 'Latvia' },
  2280: { countryCode: 'LB', countryName: 'Lebanon' },
  2282: { countryCode: 'LR', countryName: 'Liberia' },
  2284: { countryCode: 'LI', countryName: 'Liechtenstein' },
  2285: { countryCode: 'LT', countryName: 'Lithuania' },
  2286: { countryCode: 'LU', countryName: 'Luxembourg' },
  2287: { countryCode: 'MO', countryName: 'Macau' },
  2288: { countryCode: 'MK', countryName: 'Macedonia' },
  2289: { countryCode: 'MG', countryName: 'Madagascar' },
  2290: { countryCode: 'MW', countryName: 'Malawi' },
  2291: { countryCode: 'MY', countryName: 'Malaysia' },
  2292: { countryCode: 'ML', countryName: 'Mali' },
  2293: { countryCode: 'MT', countryName: 'Malta' },
  2294: { countryCode: 'MR', countryName: 'Mauritania' },
  2295: { countryCode: 'MU', countryName: 'Mauritius' },
  2296: { countryCode: 'MX', countryName: 'Mexico' },
  2297: { countryCode: 'FM', countryName: 'Micronesia; Federated States of' },
  2299: { countryCode: 'MC', countryName: 'Monaco' },
  2300: { countryCode: 'MN', countryName: 'Mongolia' },
  2301: { countryCode: 'MA', countryName: 'Morocco' },
  2302: { countryCode: 'MZ', countryName: 'Mozambique' },
  2303: { countryCode: 'MM', countryName: 'Myanmar' },
  2304: { countryCode: 'NA', countryName: 'Namibia' },
  2305: { countryCode: 'NP', countryName: 'Nepal' },
  2306: { countryCode: 'NL', countryName: 'Netherlands' },
  2307: { countryCode: 'NZ', countryName: 'New Zealand' },
  2308: { countryCode: 'NI', countryName: 'Nicaragua' },
  2309: { countryCode: 'NE', countryName: 'Niger' },
  2310: { countryCode: 'NG', countryName: 'Nigeria' },
  2311: { countryCode: 'NO', countryName: 'Norway' },
  2312: { countryCode: 'OM', countryName: 'Oman' },
  2313: { countryCode: 'PK', countryName: 'Pakistan' },
  2315: { countryCode: 'PA', countryName: 'Panama' },
  2316: { countryCode: 'PG', countryName: 'Papua New Guinea' },
  2317: { countryCode: 'PY', countryName: 'Paraguay' },
  2318: { countryCode: 'PE', countryName: 'Peru' },
  2319: { countryCode: 'PH', countryName: 'Philippines' },
  2320: { countryCode: 'PL', countryName: 'Poland' },
  2321: { countryCode: 'PT', countryName: 'Portugal' },
  2322: { countryCode: 'QA', countryName: 'Qatar' },
  2323: { countryCode: 'RO', countryName: 'Romania' },
  2324: { countryCode: 'RU', countryName: 'Russian Federation' },
  2325: { countryCode: 'RW', countryName: 'Rwanda' },
  2327: { countryCode: 'SM', countryName: 'San Marino' },
  2328: { countryCode: 'SA', countryName: 'Saudi Arabia' },
  2329: { countryCode: 'SN', countryName: 'Senegal' },
  2332: { countryCode: 'SL', countryName: 'Sierra Leone' },
  2333: { countryCode: 'SG', countryName: 'Singapore' },
  2334: { countryCode: 'SK', countryName: 'Slovakia' },
  2335: { countryCode: 'SI', countryName: 'Slovenia' },
  2338: { countryCode: 'ZA', countryName: 'South Africa' },
  2339: { countryCode: 'ES', countryName: 'Spain' },
  2340: { countryCode: 'LK', countryName: 'Sri Lanka' },
  2341: { countryCode: 'SD', countryName: 'Sudan' },
  2342: { countryCode: 'SR', countryName: 'Suriname' },
  2343: { countryCode: 'SZ', countryName: 'Eswatini' },
  2344: { countryCode: 'SE', countryName: 'Sweden' },
  2345: { countryCode: 'CH', countryName: 'Switzerland' },
  2348: { countryCode: 'TJ', countryName: 'Tajikistan' },
  2349: { countryCode: 'TZ', countryName: 'Tanzania' },
  2350: { countryCode: 'TH', countryName: 'Thailand' },
  2351: { countryCode: 'TG', countryName: 'Togo' },
  2352: { countryCode: 'TT', countryName: 'Trinidad and Tobago' },
  2353: { countryCode: 'TN', countryName: 'Tunisia' },
  2354: { countryCode: 'TR', countryName: 'Turkey' },
  2355: { countryCode: 'TM', countryName: 'Turkmenistan' },
  2356: { countryCode: 'UG', countryName: 'Uganda' },
  2357: { countryCode: 'UA', countryName: 'Ukraine' },
  2358: { countryCode: 'AE', countryName: 'United Arab Emirates' },
  2359: { countryCode: 'UK', countryName: 'United Kingdom' },
  2360: { countryCode: 'UY', countryName: 'Uruguay' },
  2361: { countryCode: 'UZ', countryName: 'Uzbekistan' },
  2362: { countryCode: 'VA', countryName: 'Holy See (Vatican City State)' },
  2363: { countryCode: 'VE', countryName: 'Venezuela; Bolivarian Republic of' },
  2364: { countryCode: 'VN', countryName: 'Vietnam' },
  2367: { countryCode: 'YU', countryName: 'Macedonia; the Former Yugoslav Republic' },
  2368: { countryCode: 'ZR', countryName: 'Congo; Democratic Republic of' },
  2369: { countryCode: 'ZM', countryName: 'Zambia' },
  2370: { countryCode: 'ZW', countryName: 'Zimbabwe' },
  2371: { countryCode: 'GT', countryName: 'Guatemala' },
  2372: { countryCode: 'BU', countryName: 'Bermuda' },
  2373: { countryCode: 'AB', countryName: 'Aruba' },
  2374: { countryCode: 'PR', countryName: 'Puerto Rico' },
  2375: { countryCode: 'TW', countryName: 'Taiwan' },
  2376: { countryCode: 'GU', countryName: 'Guam' },
  2377: { countryCode: 'HK', countryName: 'Hong Kong' },
  2378: { countryCode: 'NONE', countryName: '- None Specified -' },
  2379: { countryCode: 'KY', countryName: 'Cayman Islands' },
  2380: { countryCode: 'LY', countryName: 'Libya' },
  2381: { countryCode: 'SY', countryName: 'Syrian Arab Republic' },
  2382: { countryCode: 'YE', countryName: 'Yemen' },
  2383: { countryCode: 'CG', countryName: 'Congo; Republic of' },
  2384: { countryCode: 'MV', countryName: 'Maldives; Republic of' },
  2385: { countryCode: 'BM', countryName: 'Burma' },
  2387: { countryCode: 'C999', countryName: 'Curacao' },
  2388: { countryCode: 'FI99', countryName: 'Faroe Islands' },
  2389: { countryCode: 'GM', countryName: 'Gambia' },
  2390: { countryCode: 'G999', countryName: 'Gibraltar' },
  2392: { countryCode: 'KV', countryName: 'Kosovo' },
  2393: { countryCode: 'M999', countryName: 'Mayotte' },
  2394: { countryCode: 'RM', countryName: 'Marshall Islands' },
  2395: { countryCode: 'MD', countryName: 'Moldova; Republic of' },
  2396: { countryCode: 'MJ', countryName: 'Montenegro' },
  2397: { countryCode: 'NR', countryName: 'Nauru' },
  2398: { countryCode: 'R999', countryName: 'Reunion' },
  2399: { countryCode: 'KN', countryName: 'Saint Kitts and Nevis' },
  2402: { countryCode: 'RS', countryName: 'Serbia' },
  2404: { countryCode: 'TL', countryName: 'Timor-Leste' },
  2406: { countryCode: 'NH', countryName: 'Vanuatu' },
  2407: { countryCode: 'AX', countryName: 'Åland Islands' },
  2408: { countryCode: 'AS', countryName: 'American Samoa' },
  2409: { countryCode: 'AI', countryName: 'Anguilla' },
  2410: { countryCode: 'BV', countryName: 'Bouvet Island' },
  2411: { countryCode: 'IO', countryName: 'British Indian Ocean Territory' },
  2413: { countryCode: 'CC', countryName: 'Cocos (Keeling) Islands' },
  2415: { countryCode: 'FK', countryName: 'Falkland Islands (Malvinas)' },
  2416: { countryCode: 'GF', countryName: 'French Guiana' },
  2417: { countryCode: 'PF', countryName: 'French Polynesia' },
  2418: { countryCode: 'TF', countryName: 'French Southern Territories' },
  2419: { countryCode: 'GP', countryName: 'Guadeloupe' },
  2420: { countryCode: 'GG', countryName: 'Guernsey' },
  2421: { countryCode: 'HM', countryName: 'Heard and McDonald Islands' },
  2422: { countryCode: 'JE', countryName: 'Jersey' },
  2423: { countryCode: 'MQ', countryName: 'Martinique' },
  2425: { countryCode: 'AN', countryName: 'Netherlands Antilles' },
  2426: { countryCode: 'NC', countryName: 'New Caledonia' },
  2428: { countryCode: 'NF', countryName: 'Norfolk Island' },
  2429: { countryCode: 'MP', countryName: 'Northern Mariana Islands' },
  2430: { countryCode: 'PS', countryName: 'Palestinian Territory; Occupied' },
  2431: { countryCode: 'PN', countryName: 'Pitcairn' },
  2432: { countryCode: 'BL', countryName: 'Saint Barthélemy' },
  2436: { countryCode: 'GS', countryName: 'South Georgia and the South Sandwich Islands' },
  2441: { countryCode: 'UM', countryName: 'United States Minor Outlying Islands' },
  2442: { countryCode: 'VI', countryName: 'Virgin Islands; U.S.' },
  2443: { countryCode: 'WF', countryName: 'Wallis and Futuna' },
  2447: { countryCode: 'SS', countryName: 'South Sudan' },
  2448: { countryCode: 'SX', countryName: 'Sint Maarten' },
  2449: { countryCode: 'BQ', countryName: 'Bonaire' },
};

module.exports = { countryIdToCountry };
